"""Inline the constant pool of the flattened Ouroboros artifact.

`cKb[136][N]` (and its local alias `cTz[N]`) are positional reads into one giant
constant table. This tool rewrites every such read back to its literal value, and
labels function slots, so the flattened code can actually be read.

Usage:
    python3 tools/inline_constants.py "ouroboros_ps2 (1).luau" [output.lua]
"""

import json
import re
import sys
from collections import Counter

sys.path.insert(0, __file__.rsplit("/", 1)[0])
import luaflat  # noqa: E402


def is_quoted(text):
    return text.startswith('"') and text.endswith('"') and len(text) > 1


def unwrap(text):
    return text[1:-1] if is_quoted(text) else text


def build_maps(src, pool_expr=None):
    entries, toks = luaflat.extract_pool(src, pool_expr=pool_expr)
    values = [unwrap(e) for e in entries]
    kinds = []
    for e in entries:
        if is_quoted(e):
            kinds.append("string")
        elif re.fullmatch(r"\d+\.?\d*", e):
            kinds.append("number")
        elif e.startswith("function"):
            kinds.append("function")
        elif e.startswith("{"):
            kinds.append("table")
        else:
            kinds.append("expression")
    return entries, values, kinds, toks


def find_aliases(toks):
    """Names bound to the pool with `local X = cKb[136]` (Luau `local cTz = cKb[136]`)."""
    aliases = set()
    for i in range(len(toks) - 5):
        if toks[i][0] == "name" and toks[i][1] == "local":
            if (toks[i + 1][0] == "name" and toks[i + 2][1] == "=" and toks[i + 3][1] == "cKb"
                    and toks[i + 4][1] == "[" and toks[i + 5][1] == "136"):
                aliases.add(toks[i + 1][1])
    return aliases


def inline(src):
    entries, values, kinds, toks = build_maps(src)
    aliases = find_aliases(toks)
    fn_labels = {}
    out = []
    i = 0
    stats = Counter()
    n = len(toks)
    while i < n:
        # cKb[136][N]
        if (i + 5 < n and toks[i][1] == "cKb" and toks[i + 1][1] == "["
                and toks[i + 2][1] == "136" and toks[i + 3][1] == "]"
                and toks[i + 4][1] == "[" and toks[i + 5][1].replace(".", "").isdigit()):
            close = i + 6
            if close < n and toks[close][1] == "]":
                idx = int(float(toks[i + 5][1]))
                out.append(render(idx, entries, values, kinds, fn_labels))
                stats[kinds[idx - 1]] += 1
                i = close + 1
                continue
        # alias[N]
        if (toks[i][0] == "name" and toks[i][1] in aliases and i + 3 < n
                and toks[i + 1][1] == "[" and toks[i + 2][1].replace(".", "").isdigit()
                and toks[i + 3][1] == "]"):
            idx = int(float(toks[i + 2][1]))
            out.append(render(idx, entries, values, kinds, fn_labels))
            stats[kinds[idx - 1]] += 1
            i += 4
            continue
        out.append(toks[i][1])
        i += 1
    return "".join(out), stats, fn_labels, entries, values, kinds


def render(idx, entries, values, kinds, fn_labels):
    kind = kinds[idx - 1]
    if kind == "function":
        # keep the reference, tag it with a stable label (bodies stay in the pool)
        return "cKb[136][%d]/*%s*/" % (idx, "F%d" % idx)
    return entries[idx - 1]


def build_function_legend(text):
    """Find `["Name"] = cKb[136][N]` / `[cKb[136][N]] = ...` patterns -> name per slot."""
    names = {}
    for m in re.finditer(r'\["([^"]{1,60})"\]\s*=\s*cKb\[136\]\[(\d+)\]', text):
        names.setdefault(int(m.group(2)), set()).add(m.group(1))
    for m in re.finditer(r'cKb\[136\]\[(\d+)\]\s*=\s*\["([^"]{1,60})"\]', text):
        names.setdefault(int(m.group(1)), set()).add(m.group(2))
    return {k: sorted(v) for k, v in names.items()}


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "ouroboros_ps2 (1).luau"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "ouroboros_ps2_resolved.lua"
    json_path = sys.argv[3] if len(sys.argv) > 3 else "data/pool.json"
    src = open(path, encoding="utf-8", errors="replace").read()
    text, stats, fn_labels, entries, values, kinds = inline(src)
    legend = build_function_legend(text)
    for idx in sorted(legend)[:12]:
        print("   F%d -> %s" % (idx, ", ".join(legend[idx])[:70]))
    header = ("-- resolved constants of %s\n-- generated by tools/inline_constants.py\n"
              "-- %d pool entries: %d strings, %d numbers, %d functions, rest tables/expressions\n\n"
              % (path, len(entries),
                 sum(1 for k in kinds if k == "string"), sum(1 for k in kinds if k == "number"),
                 sum(1 for k in kinds if k == "function")))
    import os
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    open(out_path, "w", encoding="utf-8").write(header + text)
    os.makedirs(os.path.dirname(json_path) or ".", exist_ok=True)
    json.dump({"values": values, "kinds": kinds, "function_names": legend},
              open(json_path, "w"), ensure_ascii=False)
    print("inlined pool reads:", dict(stats))
    print("function slots with a name:", len(legend))
    print("wrote", out_path, len(text), "chars")
    print("wrote", json_path)


if __name__ == "__main__":
    main()
